apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-kubectl-pod-reader
  namespace: web-kubectl
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]   
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-kubectl-pod-reader
  namespace: web-kubectl
subjects:
  - kind: ServiceAccount
    name: web-kubectl
    namespace: web-kubectl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-kubectl-pod-reader
