apiVersion: v1
kind: Service
metadata:
  name: web-kubectl
  namespace: web-kubectl
spec:
  selector:
    app: web-kubectl
  ports:
    - name: http
      port: 80
      targetPort: 7681
  type: ClusterIP
